# Generated by Django 4.2.30 on 2026-07-22 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='violationlog',
            name='event_type',
            field=models.CharField(choices=[('TAB_SWITCH', 'Tab Switch / Window Blur'), ('WINDOW_BLUR', 'Window Focus Lost'), ('NO_FACE', 'No Face Detected'), ('MULTIPLE_FACES', 'Multiple Faces Detected'), ('HEAD_TURNED', 'Head Turned Away'), ('NOISE_DETECTED', 'Excessive Noise Detected'), ('MULTIPLE_DISPLAY', 'Multiple Displays Detected')], max_length=20),
        ),
    ]
